change url strings value to URL
nlogozzo/NickvisionTubeConverter pull request #135
Opened 2023-03-29 13:54 UTC by Krindog7337

Issues #134

2023-03-29 13:57 UTC, nlogozzo approved these changes

2023-03-29 14:20 UTC, fsobolev commented
I think it should be changed from "Video URL" to "Media URL" or "Video, audio or playlist URL". As I said in some other PR and in matrix, it would be better to give users more hints that the app is capable of downloading not only youtube videos, but everything yt-dlp can get. https://github.com/nlogozzo/NickvisionTubeConverter/discussions/121#discussion-5004266 is a good evidence that "Video URL" can be confusing.

2023-03-29 14:51 UTC, Krindog7337 commented
> I think it should be changed from "Video URL" to "Media URL" or "Video, audio or playlist URL". 

> it would be better to give users more hints that the app is capable of downloading not only youtube videos, but everything yt-dlp can get.

in that case, how about giving a pop-over info on right side of text input? like on pointer assistance settings (GNOME 44)

![image](https://user-images.githubusercontent.com/92032579/228577849-656b180c-0bcc-4422-9529-738b841dfd71.png)
![image](https://user-images.githubusercontent.com/92032579/228578019-f4064935-b51b-45bf-8a53-aa7b114db07f.png)

2023-03-29 16:49 UTC, fsobolev requested changes

2023-03-29 16:49 UTC, fsobolev commented on NickvisionTubeConverter.Shared/Resources/Strings.de.resx
> +    <value>Video URL (ungültig)</value>
You don't need to change anything in Strings.*.resx, Weblate will look for all changes in original Strings.resx and make all translation files match.

2023-03-29 16:50 UTC, fsobolev commented
> in that case, how about giving a pop-over info on right side of text input? like on pointer assistance settings (GNOME 44)

I like it, will implement it later 👍🏻

2023-03-30 09:08 UTC, fsobolev approved these changes

2023-03-30 09:08 UTC, merged