Added Arabic translate.
nlogozzo/NickvisionTubeConverter pull request #23
Opened 2022-11-08 19:15 UTC by fawaz006

I'm really didn't know how to build it and I also get error that say jsoncpp aren't found even it was installed, so I just coped fr.po and edit it, so I don't know if there's somthing wrong or all are ok

2022-11-08 22:00 UTC, nlogozzo requested changes
Line 226

2022-11-08 22:00 UTC, nlogozzo commented on po/ar.po
> +msgstr "Customize converter settings."
I think you forgot to translate here.

2022-11-09 10:08 UTC, fawaz006 commented on po/ar.po
> +msgstr "Customize converter settings."
wired, I remember that I translate it?

2022-11-09 14:48 UTC, nlogozzo commented
LGTM, thanks!

2022-11-09 14:48 UTC, merged