New Release v2023.2.0
nlogozzo/NickvisionTubeConverter pull request #44
Opened 2023-02-03 17:10 UTC by DaPigGuy

- Updated Flatpak dependencies
  - Checked changelogs of updated packages
  - Tested (not thoroughly, but changes to packages are mostly bug fixes)
- Updated changelog
- Bumped version

2023-02-03 17:17 UTC, nlogozzo requested changes

2023-02-03 17:17 UTC, nlogozzo commented on org.nickvision.tubeconverter.metainfo.xml
> +    <release version="2023.2.0" date="2022-02-03">
It's 2023 :) date still has 2022.

2023-02-03 17:22 UTC, DaPigGuy commented on org.nickvision.tubeconverter.metainfo.xml
> +    <release version="2023.2.0" date="2022-02-03">
Missed that :sweat_smile:

2023-02-05 18:31 UTC, nlogozzo approved these changes

2023-02-05 18:32 UTC, merged

2023-02-05 18:32 UTC, nlogozzo commented
Thanks for this :) 

I'm planning on rewriting Tube Converter in C# as I did with Denaro...eventually haha