Update CREDITS.json
nlogozzo/NickvisionTubeConverter pull request #45
Opened 2023-02-05 19:49 UTC by albanobattistella

2023-02-05 20:03 UTC, fsobolev requested changes

2023-02-05 20:03 UTC, fsobolev commented on po/CREDITS.json
> +}
you missed one `}`

2023-02-06 18:22 UTC, fsobolev approved these changes

2023-02-06 19:10 UTC, nlogozzo approved these changes

2023-02-06 23:24 UTC, merged